name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Firebase private key
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          echo $FIREBASE_PRIVATE_KEY > firebase_key.json

      - name: Deploy Streamlit app
        run: |
          streamlit run app.py  # Modify this to your actual Streamlit deployment command
